# This is a basic workflow to help you get started with Actions

name: Jupyter

# Controls when the workflow will run
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -name: Checkout
    uses: actions/checkout@v1
    
    - name: Setup Python
    uses: actions/setup-python@v4.0.0
      with:
      cache: pip
      python-version: '3.7'
    - name: Install Dependencies
    run: pip install -r my-environment.yml
    - name: Exeute Notebook # Выполнение тетрадки Jupyter
    run: jupyter-nbconvert --execute DZ1.ipynb --to html
    - name: Upload a Build Artifact # Выгрузка вывода тетрадки (артефакта задания) в html файл
    uses: actions/upload-artifact@v3.1.0
    with:
    name: Artifact
    path: DZ1.html
